version: "3.2"
services:
  php:
    build: './php/'
    networks:
      - backend
    volumes:
      - /Users/m/Work/Programer/Primelabo/Medi/source:/var/www/html/
    networks:
      frontend:
        ipv4_address: "172.18.0.10"
    tty: true
  apache:
    build: './apache/'
    depends_on:
      - php
      - db
    networks:
      - frontend
      - backend
    ports:
      - "8080:80"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
      - /Users/m/Work/Programer/Primelabo/Medi/source:/var/www/html/
    privileged: true
  db:
    image: mariadb:5.5.60
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: centos
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: centos_db
    ports:
      - "3307:3306"
    networks:
      frontend:
        ipv4_address: "172.18.0.12"
networks:
  frontend:
    ipam:
      driver: default
      config:
        - subnet: "172.18.0.0/24"
  backend:
